<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
                xmlns:alto="http://schema.ccs-gmbh.com/ALTO"
                xmlns:alto2="http://www.loc.gov/standards/alto/ns-v2#"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xhtml" encoding="utf-8" indent="yes" />

    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>Autogenerated page</title>
                <style type="text/css">
                    body { width: 94%; margin: 0; padding-left: 3%; padding-right: 3%; }
                    p { text-align: justify; }
                    <xsl:apply-templates select="//alto:Styles/alto:TextStyle" />
                    <xsl:apply-templates select="//alto2:Styles/alto2:TextStyle" />

                </style>
            </head>
            <body>
                <xsl:apply-templates select="//alto:TextBlock" />
                <xsl:apply-templates select="//alto2:TextBlock" />
            </body>
        </html>
    </xsl:template>
    <xsl:template match="//alto:Styles/alto:TextStyle">
        .<xsl:value-of select="@ID" /> {
        font-family: <xsl:value-of select="@FONTFAMILY" />;
        font-size: <xsl:value-of select="@FONTSIZE * 0.25" />em;
        }
    </xsl:template>

    <xsl:template match="//alto2:Styles/alto2:TextStyle">
        .<xsl:value-of select="@ID" /> {
        font-family: <xsl:value-of select="@FONTFAMILY" />;
        font-size: <xsl:value-of select="@FONTSIZE * 0.25" />em;
        }
    </xsl:template>

    <xsl:template match="//alto:TextBlock">
        <p>
            <xsl:attribute name="class">
                <xsl:value-of select="@STYLEREFS" />
            </xsl:attribute>
            <xsl:apply-templates select="alto:TextLine/alto:String" />
        </p>
    </xsl:template>

    <xsl:template match="//alto2:TextBlock">
        <p>
            <xsl:attribute name="class">
                <xsl:value-of select="@STYLEREFS" />
            </xsl:attribute>
            <xsl:apply-templates select="alto2:TextLine/alto2:String" />
        </p>
    </xsl:template>


    <xsl:template match="alto:TextLine/alto:String">

        <xsl:value-of select="@CONTENT" />&#160;

    </xsl:template>

    <xsl:template match="alto2:TextLine/alto2:String">

        <xsl:value-of select="@CONTENT" />&#160;

    </xsl:template>
</xsl:stylesheet>